#
# Copyright 2021 Jaroslav Chmurny
#
# This file is part of AWS Sandbox.
#
# AWS Sandbox is free software developed for educational purposes. It
# is licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Illustration of some intrinsic functions - no resource allocation.

Resources:
  # a template must contain at least one resource, so this dummy policy is here just
  # to make CloudFormation happy - it is not used 
  Dummy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${AWS::StackName}-Dummy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Action: "*"
            Resource: "*"

Outputs:
  JoinOutcome:
    Description: Outcome of !Join ["-", ["red", "green", "blue"]]
    Value: !Join ["-", ["red", "green", "blue"]]

  SplitOutcome:
    Description: Outcome of !Split [";", "1;2;4;8;16;32"]
    Value: !Join [", ", !Split [";", "1;2;4;8;16;32"]]

  CidrOutcome:
    Description: Outcome of !Cidr ["10.0.0.0/16", 3, 8 ]
    Value: !Join ["; ", !Cidr ["10.0.0.0/16", 3, 8 ]]

  AZsOutcome:
    Description: Outcome of Fn::GetAZs !Ref 'AWS::Region'
    Value: !Join
      - ";"
      - Fn::GetAZs: !Ref 'AWS::Region'
