#
# Copyright 2021 Jaroslav Chmurny
#
# This file is part of AWS Sandbox.
#
# AWS Sandbox is free software developed for educational purposes. It
# is licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

AWSTemplateFormatVersion: 2010-09-09
Description: |
  TODO

Parameters:
  ECRRepositoryNameParam:
    Description: The name of the ECR repository to be created
    Type: String
    Default: ci-cd-ecs-demo

  IAMUsernameParam:
    Description: Username of the IAM user permitted to access the created ECR repository
    Type: String

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRRepositoryNameParam
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - !Join ["", ["arn:aws:iam:::", !Ref "AWS::AccountId", ":user/", !Ref "IAMUsernameParam"]] 
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"

  # TODO
  # CodeBuildProject:
  #   Type: AWS::CodeBuild::Project
  #   Properties:
  #     Name: 

Outputs:
  RepositoryName:
    Description: The name of the created ECR repository
    Value: !GetAtt ECRRepository.RepositoryName

# see
# - https://stelligent.com/2016/05/26/automating-ecs-provisioning-in-cloudformation-part-1/
# - https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policy-examples.html