#
# Copyright 2021 Jaroslav Chmurny
#
# This file is part of AWS Sandbox.
#
# AWS Sandbox is free software developed for educational purposes. It
# is licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

AWSTemplateFormatVersion: 2010-09-09
Description: |
  Common S3 buckets used by other deployments - repository for installation artifacts, storage for access logs (S3, ELB) etc.

Parameters:
  DeploymentArtifactoryBucketNameParam:
    Description: The name of the S3 bucket that will store deployment artifacts like JAR files, ZIP files with Python code etc.
    Type: String

  S3AccessLogStoreBucketNameParam:
    Description: The name of the S3 bucket that will be used as destination for S3 access logs
    Type: String

  ELBAccessLogStoreBucketNameParam:
    Description: The name of the S3 bucket that will be used as destination for ELB access logs
    Type: String

Resources:
  DeploymentArtifactoryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DeploymentArtifactoryBucketNameParam
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DeploymentArtifactoryReadAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${AWS::StackName}-DeploymentArtifactoryReadAccess-Policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${DeploymentArtifactoryBucketNameParam}/*"

  DeploymentArtifactoryReaderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-DeploymentArtifactoryReaderRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref DeploymentArtifactoryReadAccessPolicy

  S3AccessLogStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3AccessLogStoreBucketNameParam
      AccessControl: LogDeliveryWrite
      LifecycleConfiguration:
        Rules:
          - Id: AutomaticCleanupRule
            Status: Enabled
            ExpirationInDays: 14
      # TODO: find out what will work
      # PublicAccessBlockConfiguration:
      #   BlockPublicAcls: true
      #   BlockPublicPolicy: true
      #   IgnorePublicAcls: true
      #   RestrictPublicBuckets: true

  S3AccessLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3AccessLogStoreBucketNameParam
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:ListBucket
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${S3AccessLogStoreBucketNameParam}/*"
              - !Sub "arn:aws:s3:::${S3AccessLogStoreBucketNameParam}"
            Principal:
              Service: s3.amazonaws.com

  ELBAccessLogStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ELBAccessLogStoreBucketNameParam
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: AutomaticCleanupRule
            Status: Enabled
            ExpirationInDays: 14
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ELBAccessLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: ELBAccessLogStoreBucket
    Properties:
      Bucket: !Ref ELBAccessLogStoreBucketNameParam
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:PutObject
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${ELBAccessLogStoreBucketNameParam}/*"
            Principal:
              AWS:
                - arn:aws:iam::054676820928:root
                - arn:aws:iam::156460612806:root
                - arn:aws:iam::652711504416:root
          - Action:
              - s3:PutObject
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${ELBAccessLogStoreBucketNameParam}/*"
            Principal:
              Service: delivery.logs.amazonaws.com
          - Action:
              - s3:GetBucketAcl
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${ELBAccessLogStoreBucketNameParam}"
            Principal:
              Service: delivery.logs.amazonaws.com

Outputs:
  DeploymentArtifactoryBucketName:
    Description: The name of the S3 bucket that will store deployment artifacts like JAR files, ZIP files with Python code etc.
    Value: !Ref DeploymentArtifactoryBucketNameParam

  DeploymentArtifactoryReadAccessPolicyArn:
    Description: The ARN of the IAM policy allowing read access to the deployment artifactory bucket
    Value: !Ref DeploymentArtifactoryReadAccessPolicy

  S3AccessLogStoreBucketName:
    Description: The name of the S3 bucket that will be used as destination for S3 access logs
    Value: !Ref S3AccessLogStoreBucketNameParam

  ELBAccessLogStoreBucketName:
    Description: The name of the S3 bucket that will be used as destination for ELB access logs
    Value: !Ref ELBAccessLogStoreBucketNameParam
